apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kdp-operator.fullname" . }}
  labels:
    {{- include "kdp-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "kdp-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kdp-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kdp-operator.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}