---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kdp
  name: kdp-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kdp-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kdp.nasa-pds.github.io]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [kdp.nasa-pds.github.io]
    resources: [pipelines, datainputs]
    verbs: [list, watch, patch]

  # Application: other resources we produce and manipulate.
  - apiGroups: [batch, apps, extensions]
    resources: [jobs, deployments, deployments/status]
    verbs: [create, patch, get]
  - apiGroups: [""]
    resources: [pods, services, configmaps, events]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kdp-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp-role-cluster
subjects:
  - kind: ServiceAccount
    name: kdp-account
    namespace: kdp
---